### ISSUE TITLE
how to get  toDataURL?

### ISSUE THREAD

**Issue by IsaevAlex** [mycurelabs/vue-html2canvas#19]
Hi) Please tell me, how to get   toDataURL?
this.$html2canvas(el, options).then(output => {
                    //get toDataURL()
                }).catch(error => console.error(error));

Thank you!

**Comment by larrykkk** [comment]
Hi, IsaevAlex ,just follow here https://github.com/mycurelabs/vue-html2canvas#usage
note the options
```
const options = {
  type: 'dataURL'
}
this.output = await this.$html2canvas(el, options);
```
this.output already is DataURL
